# Generated by Django 5.2.17 on 2026-09-19 10:03

import kirppuauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppuauth', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kompassi_sub',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[kirppuauth.models.UsernameValidator()], verbose_name='username'),
        ),
    ]
