# Generated by Django 5.2.13 on 2026-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0048_event_min_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_disabled',
            field=models.BooleanField(default=True, help_text='When set, registration is disabled. If not set, registration is enabled between start and end, blank being an open end.'),
        ),
    ]
