# Generated by Django 5.2.14 on 2026-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0049_event_registration_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collect_bank_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='restrict_bank_country',
            field=models.CharField(blank=True, help_text='Comma-separated list of uppercase 2-letter country codes to restrict accepted IBANs. Leave empty to allow all.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_skip',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
