# Generated by Django 5.2.17 on 2026-08-16 09:38

from django.db import migrations, models
from django.utils import timezone


def migrate_bank_lock_flag(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Vendor = apps.get_model("kirppu", "Vendor")

    # On past events that collect bank information, all vendors that have
    # a compensation receipt, lock the fields.
    (
        Vendor.objects.using(db_alias)
        .exclude(event__collect_bank_information=False)
        .exclude(event__end_date__gte=timezone.now())
        .filter(receipt__type="COMPENSATION", receipt__status="FINI")
        .distinct()
    ).update(bank_lock=True)


class Migration(migrations.Migration):
    dependencies = [
        ("kirppu", "0050_vendor_bank_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="bank_iban",
            field=models.CharField(
                blank=True,
                help_text='"!" means cleared, but previously set.',
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bank_lock",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            migrate_bank_lock_flag,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
