# Generated by Django 5.2.17 on 2026-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kirppu", "0051_vendor_bank_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organiser",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Organiser name, and registration number",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="purchase_receipt_tail",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text lines to append into each receipt.",
            ),
        ),
    ]
